# Custom Language File for Launcher Customizer

[ejs.app]
title = "OmegaClient - v1.1.1"

[ejs.landing]
mediaGitHubURL = "https://launcher.omegamc.it"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.omegamc.it"

[ejs.settings]
sourceGithubLink = "https://discord.omegamc.it"
supportLink = "https://discord.omegamc.it"

[ejs.welcome]
welcomeHeader = "BENVENUTO/A SU OMEGACLIENT"
welcomeDescription = ""
welcomeDescCTA = "Copyright © 2026 OmegaMC Studios"
