[ejs.landing]
updateAvailableTooltip = "Aggiornamento"
usernamePlaceholder = "Nome utente"
usernameEditButton = "Edit"
settingsTooltip = "Impostazioni"
serverStatus = "SERVER"
serverStatusPlaceholder = "OFFLINE"
mojangStatus = "STATO MOJANG"
mojangStatusTooltipTitle = "Servizi"
mojangStatusNETitle = "Non&nbsp;Essenziale"
newsButton = "NOTIZIA"
launchButton = "GIOCA"
launchButtonPlaceholder = "&#8226; Nessun server selezionato"
launchDetails = "Attendere prego.."
newsNavigationStatus = "{currentPage} di {totalPages}"
newsErrorLoadSpan = "Controllo notizie in corso.."
newsErrorFailedSpan = "Impossibile caricare le notizie"
newsErrorRetryButton = "Riprova"
newsErrorNoneSpan = "Nessuna novità"

[ejs.login]
loginCancelText = "Cancel"
loginSubheader = "MINECRAFT LOGIN"
loginEmailError = "* Invalid Value"
loginEmailPlaceholder = "EMAIL OR USERNAME"
loginPasswordError = "* Required"
loginPasswordPlaceholder = "PASSWORD"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "forgot password?"
loginRememberMeText = "remember me?"
loginButtonText = "LOGIN"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Need an Account?"
loginPasswordDisclaimer1 = "Your password is sent directly to mojang and never stored."
loginPasswordDisclaimer2 = "{appName} is not affiliated with Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Opzioni di accesso"
loginWithMicrosoft = "Accedi con Microsoft"
loginWithMojang = "Accedi con Mojang"
cancelButton = "Cancella"

[ejs.overlay]
serverSelectHeader = "Server disponibili"
serverSelectConfirm = "Seleziona"
serverSelectCancel = "Cancella"
accountSelectHeader = "Seleziona un account"
accountSelectConfirm = "Seleziona"
accountSelectCancel = "Cancella"

[ejs.settings]
navHeaderText = "Impostazioni"
navAccount = "Account"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "Di"
navUpdates = "Aggiornamenti"
navDone = "Fatto"
tabAccountHeaderText = "Impostazioni dell'account"
tabAccountHeaderDesc = "Aggiungi nuovi account o gestisci quelli esistenti."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Aggiungi account Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Aggiungi account Mojang"
minecraftTabHeaderText = "Impostazioni di Minecraft"
minecraftTabHeaderDesc = "Opzioni relative all'avvio del gioco."
gameResolutionTitle = "Risoluzione di gioco"
launchFullscreenTitle = "Avvia a schermo intero."
autoConnectTitle = "Connetti automaticamente al server all'avvio."
launchDetachedTitle = "Avvia il processo di gioco separatamente dal launcher."
launchDetachedDesc = "Se il gioco non è scollegato, chiudere il launcher comporterà anche la chiusura del gioco."
tabModsHeaderText = "Impostazioni della mod"
tabModsHeaderDesc = "Abilita o disabilita le mod."
switchServerButton = "Cambia"
requiredMods = "Mod richieste"
optionalMods = "Mod facoltative"
dropinMods = "Drop-in Mods"
addMods = "Aggiungi Mods"
dropinRefreshNote = "(F5 per aggiornare)"
shaderpacks = "Shaderpacks"
shaderpackDesc = "Abilita o disabilita gli shader. Tieni presente che gli shader funzioneranno in modo fluido solo su configurazioni potenti. Qui puoi aggiungere pacchetti personalizzati."
selectShaderpack = "Seleziona pacchetto shader"
tabJavaHeaderText = "Impostazioni Java"
tabJavaHeaderDesc = "Gestisci la configurazione di Java (avanzata)."
memoryTitle = "Memoria"
maxRAM = "RAM Massima"
minRAM = "RAM Minima"
memoryDesc = "La RAM minima consigliata è di 3 gigabyte. Impostare i valori minimo e massimo sullo stesso valore può ridurre il lag."
memoryTotalTitle = "Totale"
memoryAvailableTitle = "Disponibile"
javaExecutableTitle = "Eseguibile Java"
javaExecSelDialogTitle = "Seleziona l'eseguibile Java"
javaExecSelButtonText = "Scegli file"
javaExecDesc = "L'eseguibile Java viene convalidato prima dell'avvio del gioco."
javaPathDesc = "Il percorso dovrebbe concludersi con <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Opzioni JVM aggiuntive"
jvmOptsDesc = "Opzioni da fornire alla JVM in fase di esecuzione. <em>-Xms</em> e <em>-Xmx</em> non dovrebbe essere incluso."
launcherTabHeaderText = "Impostazioni del launcher"
launcherTabHeaderDesc = "Opzioni relative al launcher stesso."
allowPrereleaseTitle = "Consenti aggiornamenti pre-rilascio."
allowPrereleaseDesc = "Le versioni preliminari includono nuove funzionalità che potrebbero non essere state completamente testate o integrate.<br>Questo sarà sempre vero se si utilizza una versione preliminare."
dataDirectoryTitle = "Directory dei dati"
selectDataDirectory = "Seleziona la directory dei dati"
chooseFolder = "Scegli cartella"
dataDirectoryDesc = "Tutti i file di gioco e le installazioni locali di Java verranno memorizzati nella directory dei dati.<br>Gli screenshot e i salvataggi del mondo vengono memorizzati nella cartella dell'istanza relativa alla configurazione del server corrispondente."
aboutTabHeaderText = "Di"
aboutTabHeaderDesc = "Visualizza le informazioni e le note di rilascio per la versione corrente."
aboutTitle = "{appName}"
stableRelease = "Versione stabile"
versionText = "Versione "
sourceGithub = "Fonte (SitoWeb)"
support = "Supporto"
devToolsConsole = "Console di DevTools"
releaseNotes = "Note di rilascio"
changelog = "Registro delle modifiche"
noReleaseNotes = "Nessuna nota di rilascio"
viewReleaseNotes = "Visualizza le note di rilascio sul SitoWeb"
launcherUpdatesHeaderText = "Aggiornamenti del launcher"
launcherUpdatesHeaderDesc = "Scarica, installa ed esamina gli aggiornamenti per il launcher."
checkForUpdates = "Controlla aggiornamenti"
whatsNew = "Cosa c'è di nuovo"
updateReleaseNotes = "Note di rilascio dell'aggiornamento"

[ejs.waiting]
waitingText = "In attesa di Microsoft.."

[ejs.welcome]
continueButton = "CONTINUA"


[js.discord]
waiting = "In attesa del client.."
state = "Server: {shortId}"

[js.index]
microsoftLoginTitle = "Accesso a Microsoft"
microsoftLogoutTitle = "Esci da Microsoft"

[js.login]
login = "LOGIN"
loggingIn = "LOGGING IN"
success = "SUCCESS"
tryAgain = "Try Again"

[js.login.error]
invalidValue = "* Invalid Value"
requiredValue = "* Required"

[js.login.error.unknown]
title = "Unknown Error During Login"
desc = "An unknown error has occurred. Please see the console for details."

[js.landing.launch]
pleaseWait = "Attendere prego.."
failureTitle = "Errore durante l'avvio"
failureText = "Consulta la console (CTRL + Shift + i) per ulteriori dettagli."
okay = "Okay"

[js.landing.selectedAccount]
noAccountSelected = "Nessun account selezionato"

[js.landing.selectedServer]
noSelection = "Nessun server selezionato"
loading = "Caricamento.."

[js.landing.serverStatus]
server = "SERVER"
offline = "OFFLINE"
players = "GIOCATORI"

[js.landing.systemScan]
checking = "Controllo delle informazioni di sistema.."
noCompatibleJava = "Non compatibile<br>Installazione di Java rilevata"
installJavaMessage = "Per avviare Minecraft, è necessaria un'installazione di Java a 64 bit. {major}. Volete che ne installiamo una copia?"
installJava = "Installa Java"
installJavaManually = "Installa manualmente"
javaDownloadPrepare = "Preparazione del download di Java.."
javaDownloadFailureTitle = "Errore durante il download di Java"
javaDownloadFailureText = "Consulta la console (CTRL + Shift + i) per ulteriori dettagli."
javaRequired = "Java è richiesto<br>lancia"
javaRequiredMessage = 'A valid x64 installation of Java {major} is required to launch.<br><br>Please refer to our <a href="https://www.omegamc.it">Java Management Guide</a> for instructions on how to manually install Java.'
javaRequiredDismiss = "Capisco"
javaRequiredCancel = "Torna indietro"

[js.landing.downloadJava]
findJdkFailure = "Impossibile trovare la distribuzione OpenJDK."
javaDownloadCorruptedError = "Il JDK scaricato ha un hash errato; il file potrebbe essere corrotto."
extractingJava = "Estrazione di Java"
javaInstalled = "Java installato!"

[js.landing.dlAsync]
loadingServerInfo = "Caricamento informazioni sul server.."
fatalError = "Errore fatale"
unableToLoadDistributionIndex = "Impossibile caricare una copia dell'indice di distribuzione. Consulta la console (CTRL + Shift + i) per ulteriori dettagli."
pleaseWait = "Attendere prego.."
errorDuringLaunchTitle = "Errore durante l'avvio"
seeConsoleForDetails = "Consulta la console (CTRL + Shift + i) per ulteriori dettagli."
validatingFileIntegrity = "Verifica in corso.."
errorDuringFileVerificationTitle = "Errore durante la verifica del file"
downloadingFiles = "Download in corso.."
errorDuringFileDownloadTitle = "Errore durante il download del file"
preparingToLaunch = "Preparativi per il lancio.."
launchingGame = "Avvio del gioco.."
launchWrapperNotDownloaded = "The main file, LaunchWrapper, failed to download properly. As a result, the game cannot launch.<br><br>To fix this issue, temporarily turn off your antivirus software and launch the game again.<br><br>If you have time, please <a href=\"https://www.omegamc.it\">submit an issue</a> and let us know what antivirus software you use. We'll contact them and try to straighten things out."
doneEnjoyServer = "Fatto. Goditi il ​​server!"
checkConsoleForDetails = "Si prega di controllare la console (CTRL + Shift + i) per ulteriori dettagli."

[js.landing.news]
checking = "Controllo notizie"

[js.landing.discord]
loading = "Caricamento del gioco in corso.."
joining = "In rotta verso OmegaClient!"
joined = "Alla scoperta del regno!"

[js.overlay]
dismiss = "Congedare"

[js.settings.fileSelectors]
executables = "Eseguibili"
allFiles = "Tutti i file"

[js.settings.mstfLogin]
errorTitle = "Qualcosa è andato storto"
errorMessage = "Autenticazione Microsoft non riuscita. Riprova."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Qualcosa è andato storto"
errorMessage = "Disconnessione da Microsoft non riuscita. Riprova."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Seleziona account"
selectedButton = "Account selezionato &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Avvertimento<br>Questo è il tuo ultimo account."
lastAccountWarningMessage = "Per utilizzare il launcher, è necessario aver effettuato l'accesso ad almeno un account. In seguito sarà necessario accedere nuovamente.<br><br>Sei sicuro di volerti disconnettere?"
confirmButton = "Sono sicuro che"
cancelButton = "Cancella"

[js.settings.authAccountPopulate]
username = "Nome utente"
uuid = "UUID"
selectAccount = "Seleziona account"
selectedAccount = "Account selezionato ✓"
logout = "Esci"

[js.settings.dropinMods]
removeButton = "Rimuovi"
deleteFailedTitle = "Impossibile eliminare<br>Drop-in Mod {fullName}"
deleteFailedMessage = "Assicurati che il file non sia in uso e riprova."
failedToggleTitle = "Impossibile cambiare stato<br>Una o più mod drop-in"
okButton = "Okay"

[js.settings.serverListing]
mainServer = "Server Principale"

[js.settings.java]
selectedJava = "Selected: Java {version} ({vendor})"
invalidSelection = "Invalid Selection"
requiresJava = "Requires Java {major} x64."
availableOptions = "Available Options for Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pre-release"
stableReleaseTitle = "Stable Release"
releaseNotesFailed = "Failed to load release notes."

[js.settings.updates]
newReleaseTitle = "New Release Available"
newPreReleaseTitle = "New Pre-release Available"
downloadingButton = "Downloading.."
downloadButton = 'Download from GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Close the launcher and run the dmg to update.</span>'
latestVersionTitle = "You Are Running the Latest Version"
checkForUpdatesButton = "Check for Updates"
checkingForUpdatesButton = "Checking for Updates.."

[js.settings.msftLogin]
errorTitle = "Microsoft Login Failed"
errorMessage = "We were unable to authenticate your Microsoft account. Please try again."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Fatal Error: Unable to Load Distribution Index"
fatalErrorMessage = "A connection could not be established to our servers to download the distribution index. No local copies were available to load. <br><br>The distribution index is an essential file which provides the latest server information. The launcher is unable to start without it. Ensure you are connected to the internet and relaunch the application."
closeButton = "Close"

[js.uibinder.validateAccount]
failedMessageTitle = "Failed to Refresh Login"
failedMessage = "We were unable to refresh the login for <strong>{account}</strong>. Please select another account or login again."
failedMessageSelectAnotherAccount = "We were unable to refresh the login for <strong>{account}</strong>. Please login again."
loginButton = "Login"
selectAnotherAccountButton = "Select Another Account"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Controllo aggiornamenti in corso..."
installNowButton = "Installa Ora"
checkForUpdatesButton = "Controlla aggiornamenti"

[js.auth.microsoft.error]
noProfileTitle = "Error During Login:<br>Profile Not Set Up"
noProfileDesc = "Your Microsoft account does not yet have a Minecraft profile set up. If you have recently purchased the game or redeemed it through Xbox Game Pass, you have to set up your profile on <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>If you have not yet purchased the game, you can also do that on <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Error During Login:<br>No Xbox Account"
noXboxAccountDesc = "Your Microsoft account has no Xbox account associated with it."
xblBannedTitle = "Error During Login:<br>Xbox Live Unavailable"
xblBannedDesc = "Your Microsoft account is from a country where Xbox Live is not available or banned."
under18Title = "Error During Login:<br>Parental Approval Required"
under18Desc = "Accounts for users under the age of 18 must be added to a Family by an adult."
unknownTitle = "Unknown Error During Login"
unknownDesc = "An unknown error has occurred. Please see the console for details."

[js.auth.mojang.error]
methodNotAllowedTitle = "Internal Error:<br>Method Not Allowed"
methodNotAllowedDesc = "Method not allowed. Please report this error."
notFoundTitle = "Internal Error:<br>Not Found"
notFoundDesc = "The authentication endpoint was not found. Please report this issue."
accountMigratedTitle = "Error During Login:<br>Account Migrated"
accountMigratedDesc = "You've attempted to login with a migrated account. Try again using the account email as the username."
invalidCredentialsTitle = "Error During Login:<br>Invalid Credentials"
invalidCredentialsDesc = "The email or password you've entered is incorrect. Please try again."
tooManyAttemptsTitle = "Error During Login:<br>Too Many Attempts"
tooManyAttemptsDesc = "There have been too many login attempts with this account recently. Please try again later."
invalidTokenTitle = "Error During Login:<br>Invalid Token"
invalidTokenDesc = "The provided access token is invalid."
tokenHasProfileTitle = "Error During Login:<br>Token Has Profile"
tokenHasProfileDesc = "Access token already has a profile assigned. Selecting profiles is not implemented yet."
credentialsMissingTitle = "Error During Login:<br>Credentials Missing"
credentialsMissingDesc = "Username/password was not submitted or password is less than 3 characters."
invalidSaltVersionTitle = "Error During Login:<br>Invalid Salt Version"
invalidSaltVersionDesc = "Invalid salt version."
unsupportedMediaTypeTitle = "Internal Error:<br>Unsupported Media Type"
unsupportedMediaTypeDesc = "Unsupported media type. Please report this error."
accountGoneTitle = "Error During Login:<br>Account Migrated"
accountGoneDesc = "Account has been migrated to a Microsoft account. Please log in with Microsoft."
unreachableTitle = "Error During Login:<br>Unreachable"
unreachableDesc = "Unable to reach the authentication servers. Ensure that they are online and you are connected to the internet."
gameNotPurchasedTitle = "Error During Login:<br>Game Not Purchased"
gameNotPurchasedDesc = "The account you are trying to login with has not purchased a copy of Minecraft. You may purchase a copy on <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Unknown Error During Login"
unknownErrorDesc = "An unknown error has occurred. Please see the console for details."
